### ISSUE TITLE
Adjustable Hover Time before Window Preview

### ISSUE THREAD

**Issue by metafarion** [klangman/CassiaWindowList#11]
Ok, now that I have my setup fully working, I have a wishlist item :-P

I would like to be able to adjust the time I hover the mouse over a thumbnail before the full window preview appears.  I like my thumbnails to show up pretty quickly, but the full preview to take a full second or even two, because it's large and disorienting, and I want the system to only do it if I really mean it.  This is doubly true for full previews that pop in from other workspaces.

**Comment by klangman** [comment]
Sure.. That's easy enough to do. 

I suspect the best behaviour would be to wait for the specified delay time before showing the first full size preview, but if a preview is already showing and you move the mouse to another thumbnail, then the preview should instantly switch to the new window rather then just removing the current preview and waiting another delay period before showing a preview of the new window?

**Comment by klangman** [comment]
I pushed a change to implement this: https://github.com/klangman/CassiaWindowList/commit/3a429f084b8f66fc57782b541e7e4d13643367cb

I'll push to cinnamon spices in a few days after some testing time.

**Comment by metafarion** [comment]
Yeah, that sounds reasonable, in for one full size preview, in for all full size previews.

**Comment by klangman** [comment]
CWL 2.0.1 was just merged at cinnamon-spices. This has the delay option you asked for. 

So I guess we can close this feature request now?

**Comment by klangman** [comment]
> Oh, it's beautiful, I love it. You don't have a tip jar somewhere do you?

No.. Not yet.. Maybe I should register with one of those sites.. One day I guess..  For now just give CWL a like on cinnamon-spices and a star here on github will be good.. Thanks!
