### ISSUE TITLE
Thumbnails prevent workspace switching?

### ISSUE THREAD

**Issue by metafarion** [klangman/CassiaWindowList#12]
Hey, I just noticed today that if there is a thumbnail displayed from hovering the pointer over a window list item, or over the the thumbnail itself, my keyboard commands for switching workspaces don't respond.  This isn't really an intentional workflow thing, it's just... sometimes I remember "oh yeah, the thing I'm looking for is on workspace 4" in the middle of perusing the window list.

Is this maybe a side effect of something I have configured in the CWL settings, or is it a consequence of a more fundamental interaction with the window manager?

**Comment by klangman** [comment]
Ya, there is something messed up about using the keyboard when the thumbnail menu is open. For me I can use the arrow keys to select between some (but not all) windows. I think it would be best if it worked like the grouped window list in that the thumbnail menu does not respond to keyboard input. I had noticed this a while back and meant to look into it but then I got on to something else and forgotten about it.  I hadn't noticed how it was preventing workspace switching hotkeys. I'll look into it and see what I can do to fix this.

**Comment by klangman** [comment]
@metafarion I just checked-in this change: https://github.com/klangman/CassiaWindowList/commit/708176361cc2271f5b1c518395e6160fd800c2ed

This addresses the workspace switching hotkeys and the cursor-key behaviour when the thumbnail menu is open. I'll push this to cinnamon-spices in the coming few days after I have tested this a bit more.

**Comment by klangman** [comment]
@metafarion The fix has now been merged in to cinnamon-spices. I think we can call this one done?

**Comment by metafarion** [comment]
Ooh nice, I just updated and tested it. Looks real good.  Thanks again!
