### ISSUE TITLE
Workspace indicators

### ISSUE THREAD

**Issue by metafarion** [klangman/CassiaWindowList#13]
I think it would be really handy to be able to see which workspace a window belongs to just by looking at its task list icon or thumbnail.  It would allow you to immediately locate "The terminal window I have open in workspace 3", for example, which is very useful if you like to have your workspaces are segregated by topic, but you also like to have "Include windows from all workspaces" enabled.  Particularly in the Pooled layout, what if there was a little numeric indicator in the upper right corner of the icon/label?  This would be handy in thumbnail view as well.

**Comment by klangman** [comment]
I think I will add an option to select what the number label/badge will show; Application group window count, workspace number or monitor number. Having more than one won't be an option for now at least.

**Comment by klangman** [comment]
If you are using a GIT version then to you can get the latest and the option will be there to select what the contents of the number label will be, window-count, Workspace number or Monitor number. If if are using the cinnamon-spices version then it will be a week or so before I update cinnamon spices.

**Comment by klangman** [comment]
I pushed the changed to cinnamon-spices. You can upgrade now to get the new features.

**Comment by metafarion** [comment]
Oh hey, this is super cool!  I can easily tell where all my windows are without even clicking anything.  "Oh hey, I have a terminal open on Workspace 5 that I forgot about"

I am seeing some inconsistent behavior in how the numbers are assigned in the case of Grouped windows, but it may be a byproduct of a ton of windows being already open while I'm fiddling with the settings.  I'll be able to test more thoroughly later.

Thanks for all your work on my funny little ideas.  I owe you several coffees coffees now.

**Comment by metafarion** [comment]
One small thought on the config panel: You might consider greying out the Monitor Number or Workspace Number label options depending on what the user has selected in the General tab for "Only show windows on the same monitor" or "Include windows from all workspaces" respectively, since those numbers are meaningless if the list is confined to one monitor or workspace.

...although, we also don't want the user to have unavailable options but not understand WHY they're unavailable.  Not totally sure about this.

**Comment by klangman** [comment]
> You might consider greying out the Monitor Number or Workspace Number label options depending on what the user has selected in the General tab

The json file that defines the config options is kinda limited. I can add dependencies for an entire option which will show the option (or not) depending on some other state, but I don't know of a way to add/remove drop down list options based on some dependency. 

> I am seeing some inconsistent behavior in how the numbers are assigned in the case of Grouped windows

The most recently focused window should be the one that defines what is shown in the number label of a grouped button. But I just tested it out and indeed the number is not changing when I focus a different window in the group. I'll fix that. Thanks for spotting the issue.

**Comment by klangman** [comment]
This commit should fix the issue: 3a7d185b816d0cdcd79330618aa1287dfde4ae70

I'll push to cinnamon-spices in a few days after some testing time.

**Comment by klangman** [comment]
I pushed another update to cinnamon-spices. This one includes code to show the workspace/monitor on each Thumbnail menu item (when appropriate).

I think this completes the features you originally ask for. Are we good to close this now or is there something else I have yet to implement?

**Comment by metafarion** [comment]
This looks fantastic, thanks so much.  Sweet organization, where have you been all my life?!

**Comment by klangman** [comment]
Thanks for the suggestions!! I'll close this issue now.
