### ISSUE TITLE
Hide labels for apps on other workspace.

### ISSUE THREAD

**Issue by SVerstov** [klangman/CassiaWindowList#14]
Hello! Firstly - thanks! Your applet is the best part of cinnamon =)
I'm missing one thing - the analog of "Hide labels for minimized buttons" but for apps in other workspaces.

Thanks a lot!

**Comment by klangman** [comment]
Glad you like the applet.

Let me make sure I understand what you are asking for... You want to have a new option that allows you to hide labels for windows on other workspaces. Did I get that right?

If I were to add that, I should also have the same thing for windows on other monitors as well. Just thinking about how I can fit this in using as little space as possible in the config menus. I could use a drop down list and allow the user to hide labels for one of three options (Minimized windows, On other workspaces, On other monitors). This would mean you can have one of these but not more then one at the same time.

I'll think about it for a bit. Thanks for the suggestion!

**Comment by klangman** [comment]
OK.. I added the drop-down list to my local version is it seems to be working. Need some time to test it more and to finish some other work before I push it to github, then a bit more time before pushing to cinnamon-spices.

**Comment by klangman** [comment]
Finally added the option to my github version. https://github.com/klangman/CassiaWindowList/commit/de5e885ae5f5ce51ea35189a9c7177c06ebc59d9

If you want to you try it, you can use the GH source, if not you'll have to wait a bit longer before I push the changes to cinnamon-spices.

**Comment by klangman** [comment]
@SVerstov I just pushed CassiaWindowList version 2.3.0 to cinnamon spices. You can upgrade to this version by using the Cinnamon Applets tool in the Cinnamon setting. Hope this feature works the way you had hopped. 

If everything is working as you expected then we can close this issue. Let me know. 
Thanks for the suggestion!

**Comment by SVerstov** [comment]
Great! It works perfect! Thank you very much ! 😃
