### ISSUE TITLE
Option to order windows in thumbnail preview list by workspace/monitor ID

### ISSUE THREAD

**Issue by bowars** [klangman/CassiaWindowList#15]
Hello, thank you so much for this project!

Could you possibly add an option to order the window previews displayed in the thumbnail hover menu by their workspace ID and monitor ID? I tend to have a lot of windows open for some programs, and this would really help make switching more intuitive for me.

**Comment by klangman** [comment]
I am glad you like the applet!

I am just in the middle of adding drag and drop support of Thumbnail menu items. This will allow you to rearrange the windows yourself. Maybe that's good enough, but if not then I can consider adding a option to sort by Monitor/Workspace for grouped buttons. For pools I have to follow the order on the window-list, but it doesn't sound like you use the window pooling feature anyhow?

**Comment by klangman** [comment]
Here is what I am thinking.. When a new option is enabled I will sort grouped windows by workspace, then monitor. This sort order will be enforced so the user will be prevented from reordering the list using drag-and-drop within the Thumbnail menu. The sort will happen when new windows are added and when changing an application to be grouped manually.

I had considered adding a third sort criteria, by X axis, so (for example) the left most window in the Thumbnail menu for any group of windows on a particular workspace/monitor would be the window that exists on the desktop closest to the left. But that would mean the sort order would need to be calculated each time the Thumbnail menu is opened, and the order would not be consistent which might be more confusing.

Anyhow, I have started working on it.

**Comment by bowars** [comment]
Sounds ideal as proposed - thank you very much for your careful thought.

**Comment by klangman** [comment]
I added the changes here: 151c211b9e46e96b5c357597941782ca6a6b8924

You can try it out if you want to use my Github source, but if you want to stick with the cinnamon-spices version then you will need to wait a bit longer as I do some more testing before pushing the changes to the cinnamon-spices repository.

**Comment by klangman** [comment]
> It works wonderfully, thanks! The only issue I noticed was that it didn't sort existing windows after enabling the option. I restarted cinnamon as an easy way to reload, and then it was fine.

That's odd, it should have worked.. I'll test it a bit more and see if I can recreate that issue.

**Comment by klangman** [comment]
@bowars I just pushed CassiaWindowList Version 2.3.0 to cinnamon spices. This has the feature you requested.

If all is working well then I think we can close this issue now?
Thanks for the suggestion!

**Comment by bowars** [comment]
Great, I hope other people find some use for it as well! Thanks once again.

**Comment by klangman** [comment]
> > It works wonderfully, thanks! The only issue I noticed was that it didn't sort existing windows after enabling the option. I restarted cinnamon as an easy way to reload, and then it was fine.
> 
> That's odd, it should have worked.. I'll test it a bit more and see if I can recreate that issue.

Just for completeness... I was never able to recreate the sorting issue you reported.. If you happen to hit it again and have some content that might help me recreate, let me know. Thanks again!
