### ISSUE TITLE
Thumbnail preview list does not always update

### ISSUE THREAD

**Issue by bowars** [klangman/CassiaWindowList#17]
I'm having an issue where, on occasion, the list of windows in the thumbnail preview list appears to be out of date when I unhide the bar and hover. Sometimes windows which have been closed are still listed (with an odd blank preview), and sometimes just the window titles are out of date (e.g. tab name or open file name). This has happened with multiple programs (e.g. Firefox, Sublime). If I move to hover over another icon and then back again, the list updates properly. If I move away from the list entirely and go back again, the list also updates properly.

I've been experiencing this for a while (perhaps this was even the cause of the issue with not sorting existing windows in https://github.com/klangman/CassiaWindowList/issues/15 ? Unsure), but have held off on reporting as I can't seem to find a reliable way to reproduce the problem, despite frantically opening/closing windows and switching workspaces to try and do so! I would estimate it happens approximately once every couple of hours in normal use though.

**Comment by klangman** [comment]
I hit the same issue a while back, but I had thought I fixed it with version 2.3.0

"Fix a cases where Thumbnail menus can contain stale window titles or even contain windows that have been closed".

Are you using a version older than 2.3.0?? Version 2.3.0 is the same version where the "Option to sort Thumbnail menus" feature was added.

**Comment by bowars** [comment]
I can't find where to see the exact version number that I'm using (not in About?) but I certainly have the sorted thumbnail menus.

**Comment by bowars** [comment]
Oh I'm sorry - I thought I'd switched to using the official version, but I was still running a locally checked out version which had the grouped thumbnails commit but not your fix commit (https://github.com/klangman/CassiaWindowList/commit/88adb67af29e8277f356c4fc4c0a9ac5f977c641). I've corrected that now, so I'll close this issue and reopen if the problem occurs again.

**Comment by klangman** [comment]
I should set the "version" for my Github code to "github" or something like that so it's easy to spot when you are using a github development version.
