### ISSUE TITLE
Auto-zoom when thumbnail preview list is too long

### ISSUE THREAD

**Issue by bowars** [klangman/CassiaWindowList#18]
It would be handy to have an option to automatically zoom out on the thumbnail preview list when the list is too long to fit on screen (perhaps up to a maximum zoom out level to cope with very long lists?).

Alternatively, remembering the zoom level for certain programs would also mostly solve the problem (which is that I find myself always having to zoom out the list in some cases).

**Comment by klangman** [comment]
> Alternatively, remembering the zoom level for certain programs would also mostly solve the problem (which is that I find myself always having to zoom out the list in some cases).

Actually you can already do that. In the config, Thumbnails tab, in the "Adjust thumbnail window sizes using the scroll-wheel" drop down, select "On (application default)". Now if you open the Thumbnail menu for a give application, then use the mouse scroll-wheel to adjust the size of the window-thumbnails, it will remember that thumbnail size for that application and use that size the next time the thumbnail menu is opened.

Is that what you were looking for?

**Comment by bowars** [comment]
Oh I hadn't spotted that one - perfect, thanks!
