### ISSUE TITLE
Thumbnail preview zoom level not synchronized across workspaces (application default mode)

### ISSUE THREAD

**Issue by bowars** [klangman/CassiaWindowList#19]
Have just enabled the application default mode as discussed in https://github.com/klangman/CassiaWindowList/issues/18 , and the zoom level is indeed remembered on the workspace where I zoom, but the zoom level isn't synchronized between workspaces. Additionally, it doesn't seem to be saved when Cinnamon restarts, but I'm not sure if that's intentional or not.

**Comment by klangman** [comment]
Yes, it is a per-workspace setting currently and it is not saved in the setting json file.

Let me think on it for a bit, but I suspect that making it global (across-workspaces) and saved in the settings is a fine idea. Just need to consider if that would cause any issues and if there is any strong reason someone might not want that behaviour or if I can make it a hard-coded behaviour change.

Thanks for reporting the issue.

**Comment by bowars** [comment]
Thank you for the rapid responses on all of my feedback - your work is very much appreciated!

**Comment by klangman** [comment]
I just pushed changes to make the Thumbnail window size changes via the Scrollwheel to be workspace global and to persist across cinnamon restarts.  

https://github.com/klangman/CassiaWindowList/commit/62f18808c9b2bacad343e5bb19fb20d1a76743d6

Let me know if it works as you expected now. I'll push to cinnamon-spices in a while after I do more testing.

**Comment by bowars** [comment]
Works exactly as expected in an initial try! Will let you know if I run into any issues.

**Comment by klangman** [comment]
I pushed the changes to cinnamon-spices now as well. I guess we can close this issue now?

**Comment by bowars** [comment]
Yes indeed - working great. Thank you!
