### ISSUE TITLE
welcome screen on restart

### ISSUE THREAD

**Issue by bahehs** [klangman/CassiaWindowList#21]
Whenever I restart my computer, I get the welcome screen. I am not sure why its not saving the config loading it automatically. I am using mint 22  and cinnamon 6.2.9. 

It was installed from applets in mint settings and in advanced I have set the option "settings backup name". I attached the config that I am using. Please let me know if other information is needed.

[casia.json](https://github.com/user-attachments/files/17050496/casia.json)

![Screenshot from 2024-09-18 15-11-56](https://github.com/user-attachments/assets/ba3444f8-63af-42b3-a5c3-f5ef01910230)

**Comment by klangman** [comment]
That is strange.. 

```
    "runWizard": {
        "type": "generic",
        "default": 1,
        "value": 1
    },
```
The above entry in your json is why it's opening on startup.

The following code should be preventing the welcome screen on a second load:

https://github.com/klangman/CassiaWindowList/blob/e80fcb356d7a0176915de89815c691dc4dd810ac/CassiaWindowList%40klangman/SetupWizard.py#L148

Can you run `tail -f ~/.xsession-errors` in a terminal then right-click on a empty space on the panel, click `Troubleshoot->Restart Cinnamon`. After that check the new output in the terminal running tail and see if you see any errors that might help us understand what is preventing the code from resetting the "runWizard" value to 0.

The code looks for the json file in two possible locations.

1. ~/.config/cinnamon/spices/CassiaWindowList@klangman/<instance_id>.json
2. ~/.cinnamon/configs/CassiaWindowList@klangman/<instance_id>.json

If it does not find the 1st file then it looks for the 2nd file.  In which location is your json being stored??  I think modern Mint versions all use the 1st location.

After collecting this data you can use a text-editor to modify the json `"value": 1` line under `"runWizard"` so the **1** is changed to **0**. After that, a restart of cinnamon should not show the welcome screen.

Thanks for reporting the issue. Hopefully we can find out what happened here so I can adjust the code to make sure this does not happen for others in the future.

**Comment by klangman** [comment]
@bahehs Any update on this issue. Did any of my suggestions give you any insights about what might be going wrong?

**Comment by bahehs** [comment]
So I killed cinnamon using pkill -HUP -f "cinnamon --replace"
and got this 
[debugCasia.txt](https://github.com/user-attachments/files/17133957/debugCasia.txt)

Found the config in the first one listed ~/.config/cinnamon/spices/CassiaWindowList@klangman/<instance_id>.json and made the manual change. I have restarted computer 3 times now and data persists.

Thanks for this nice applet. I used to use 7+ Taskbar on windows and this allows me to do the same thing. My most used apps that I only need 1 instance of like spotify, keepass, clock are without labels and others like file manager, text editors, Firefox have labels so I can quickly differentiate. Appreciate the support and hard work!

![2024-09-25_10-27](https://github.com/user-attachments/assets/1f023ec1-e020-4167-93ab-f8020f8d650b)

**Comment by klangman** [comment]
I made the change in this commit https://github.com/klangman/CassiaWindowList/commit/fdae1e5508a4cf1f4ee5110745e716d174ee63ed

I hope this fixes the issue.. I'll push to cinnamon-spices in a few days.

**Comment by klangman** [comment]
@bahehs  Version 2.3.5 on Cinnamon Spices has the changes that I hope will fix this issue, but since I was not able to recreate the issue I can't be 100% sure that the issue is really resolved. Should we close this now, you can open a new issue if the issue ever happens again?

**Comment by bahehs** [comment]
Yes please, thank you!
