### ISSUE TITLE
Unable to Hover Item on Taskbar and Open Window

### ISSUE THREAD

**Issue by AeraAera** [klangman/CassiaWindowList#24]
Hello! A current bug I am witnessing under all testing circumstances is the inability to hover a dragged/held item onto a taskbar window (regardless of minimized/maximized state of the window) and drag that held item into the window.

For example, one might wish to drag a photo from a file explorer into an email by dragging from its location, hovering the cursor over the minimized browser to open it, then drop it into an email. Or simply folder-to-folder drag-and-drop. Hovering over a window on the taskbar results in a "no" cursor state of a crossed-through circle. No preview is shown when the preview settings are enable and when it functions normally without an item being dragged.

**Comment by klangman** [comment]
So you want to have the associated window restored when hovering over a window-list button while dragging a file?  Do I have that right?

**Comment by AeraAera** [comment]
Thanks for the quick comment. That sounds to be the correct interpretation to me. If such an option could be implemented without undue burden, that would be greatly appreciated. The current workaround is simply using two monitors when I need two fullscreen windows, but if I'm forced one only on for work purposes, I can't drag items between two fullscreen windows on the same monitor.

This is the only bug or missing feature that I've found in Cassia Window List, which has been functional fantastically. I also realize now that I likely should have made this issue note on the Cinnamon applet page.

**Comment by klangman** [comment]
Finally got around to addressing this issue. I hope commit does what you wanted? 

https://github.com/klangman/CassiaWindowList/commit/29d1cd504e675dfc0b539f6cf42b33f11facc14a

Rereading your original issue text leads me to think that I need to do a bit more work on this. I suspect you would want the thumbnail menu to open if you hover while dragging an object over a grouped window-list button?

**Comment by AeraAera** [comment]
Wonderful news! Your update is exactly what I was hoping for. I personally do not used taskbar groupings, so the next step on your mind won't impact me with my current setup, but I imagine that there will be users who would benefit from such an update.

Again, much appreciated. This makes dragging and dropping items around significantly easier.

**Comment by klangman** [comment]
@AeraAera This code change is now in Cinnamon Spices as well (version 2.3.9).
