### ISSUE TITLE
[Feature Request] Ability to disable animation on click.

### ISSUE THREAD

**Issue by Patrock404** [klangman/CassiaWindowList#4]
The title is self explanatory, I think the ability to toggle off the animation that plays when clicking on a pinned application would be great.

Played around with everything else, I really like this applet.

**Comment by klangman** [comment]
Sure, easy enough to do, only issue is where to stuff the option. I guess the "General" tab will just need expand a bit. I'll work on it in the coming days.

**Comment by klangman** [comment]
This change is now pushed to cinnamon-spices, so I thank we can call this done. Thanks for the suggestion.
