### ISSUE TITLE
[Feature Request] Hover Peek

### ISSUE THREAD

**Issue by notrealdan** [klangman/CassiaWindowList#7]
The default Cinnamon "Grouped Window List" applet has a feature called Hover Peek.  With that enabled, you can hover your mouse over a thumbnail to cause the corresponding window to appear in the foreground.  If you move your mouse away, the window goes back to wherever it was (underneath other windows, minimized, etc.).  I find it a good way to find the one window I want from among several.  Would it be possible to add this feature to this applet?

**Comment by klangman** [comment]
I did see that feature in the Grouped Window List but it was never something I wanted to use so I never attempted to implement it. I'll take a look and see about implementing it now.

**Comment by klangman** [comment]
I see how it works, they create a window clone (just like the thumbnail windows, only full size). I don't think it will be too hard to do, just have to think about where to put the option.

**Comment by notrealdan** [comment]
Great, thanks!  If it helps, here's where they put the option:
![image](https://github.com/klangman/CassiaWindowList/assets/28198633/354101da-7110-4054-a600-a90243df318e)
Of course, it's up to you how/if you wish to implement it.  Thanks again!

**Comment by klangman** [comment]
That's a lot of new options.. Wonder if the fade-in/out options are really needed? Do you think people often change it from default???

**Comment by notrealdan** [comment]
Not needed for me.  I've left them default and am happy to keep it simple.  I suppose if others want them, they can speak up and request them.  :)

**Comment by klangman** [comment]
OK,

Here is a quick implementation of what you asked for. Currently missing a fade-in/out, but I will add that in a future update. 

https://github.com/klangman/CassiaWindowList/commit/95065b98f2cd7d556068abce272b8df63e391ec6

If you have some time to try it out and let me know if you find any issues with it, I would appreciate it.

**Comment by notrealdan** [comment]
I tried it and it works great!  Thanks for such a quick job on this!  I'll play with it more tomorrow and will let you know if I run into any issues.

**Comment by notrealdan** [comment]
I have run into an odd issue a couple of times today where a window appears to be staying on top of other windows and cannot be interacted with, and I think it might actually be a "peek" not going away as it should.  For lack of a better term, I'll call it a "persistent peek."  The persistent peek stays on top of other windows, won't go away until the original program is closed/killed, and can't be moved or interacted with directly.  Clicks on it instead affect windows that it's on top of.  If I'm able to move the real window for whatever program it's showing, I can interact with that and visual changes on the real window are replicated in the persistent peek.  Killing the program that it's a peek of does remove the persistent peek.

So far I've only observed this issue with windows from programs like Remmina and VMware Console, so maybe it has something to do with how they grab the mouse to control the remote system, but that's a wild guess.  It could be coincidental, as I've spent a lot of time in those today.

**Comment by notrealdan** [comment]
A little more info...  It doesn't seem to be related to Remmina or VMware console at all.  I can replicate the issue by opening any program (I tested with Nemo and Firefox), hovering over the thumbnail to get the peek to appear, and right-clicking on the thumbnail.  That causes the right-click menu to come up like normal, but also makes the peek become persistent.

**Comment by klangman** [comment]
Ya. That's a issue in the code where I fail to dispose of the window clone.  You can get rid of the clone only by closing the original window (as you pointed out) or by restarting cinnamon. I'll push a fix tonight.

**Comment by klangman** [comment]
Here is a fix for the hover peek issue you found.

https://github.com/klangman/CassiaWindowList/commit/3711d7e5ca489dc78f792cc9eb4b4c93ade53264

**Comment by notrealdan** [comment]
That seems to have done the trick, thanks!  I'll keep an eye out for anything else odd, but so far so good.

**Comment by klangman** [comment]
I added some refinement to the hover peeking (added a delay to avoid needless hover-peek windows and fade-in/out effects).  I also added an option to enable hover peek for window-list buttons rather then it being used only for Thumbnail menus.

https://github.com/klangman/CassiaWindowList/commit/d351dc74b399fe676f08894c05de764d20bceb9d

Let me know if you spot any problems after these changes. Thanks!

**Comment by notrealdan** [comment]
No problems so far, but I'll have more time with it tomorrow.

**Comment by notrealdan** [comment]
I haven't run into any problems.  The fade in/out is a welcome addition!

My only comment is that it would be nice for the thumbnail menu to also fade in/out in the same way.  It would be a nice touch and also more consistent.

**Comment by klangman** [comment]
It should have the same fade-in/out effect actually, as well as the slight delay before showing the clone so that when you are quickly sliding the mouse over the thumbnail menu it only pops up the clone when you are on a particular Thumbnail for 70ms or longer.  If you don't see the fade-in/out then I will need to look into that. The fade-in/out is only 270ms I think, so it's a quick fade time. 

Another thing.. I am working on a new option idea... If you hover over a window-list button or Thumbnail menu and then leave the panel or Thumbnail menu without clicking (when this new option is enabled) it will activate the window. With that option and the hover-peek enabled you can just roll your pointer over the window-list/Thumbnail menu and when you see the window you want, you can just move the pointer off the panel/menu and that window will have the focus. Does this sound like something you might use? I am not sure yet if I would use the feature, but I suspect some people might like it. The only issue is sometimes you might mistakenly move the mouse onto the panel and the window with the focus would change.

**Comment by notrealdan** [comment]
The thumbnail menu is definitely not fading in or out for me.  Is there a setting I might have changed to turn that off by accident?

I don't think I would use that feature you mentioned, both because of the possibility of accidental focus changes (like you said) and that workflow is distinctly different from my current "muscle memory."  But, I can see that some people might like the option.

**Comment by klangman** [comment]
There is no setting to adjust the fade-in/out time or to disable it short of disabling the hover peek option for Thumbnail menu item hovering. 

Are you 100% sure you have updated the applet with the latest and that you restarted cinnamon after updating the code?

I think we are on the same page here, but just to be 100% sure: we are talking about the fade-in/out effect on the full window peeking when hovering over a Thumbnail menu items and not the Thumbnail menu it's self, right?

**Comment by notrealdan** [comment]
I am fully up-to-date (getting the development version via git, as described in your readme) and have rebooted the whole laptop more than once today.  I checked again just now to be absolutely sure.

But, I think I just wasn't clear.  I mean the thumbnail menu itself does not fade in/out, and it would be a nice touch if it did also.  The thumbnails appear instantly.  The full window peeking does indeed fade in/out as expected.

**Comment by klangman** [comment]
Ah, OK.. We were not on the same page after all. 

I agree, a fade-in/out for the Thumbnail menu would be a nice touch. I added it in my local source and it does make the Thumbnail menu seem less harsh. I will push it to github soon, along with my "new idea" option which might not get used by anyone but I like the idea so ill add it anyhow :-)

**Comment by klangman** [comment]
Here is the commit with the Thumbnail menu fade-in/out effects along with some other options and refinements.

https://github.com/klangman/CassiaWindowList/commit/f539301ea173e9d47b863f1b02382ee64b4f051b

I think it now covers everything we talked about in this issue?

**Comment by notrealdan** [comment]
Yes, it's working great!  I think you can close this.  Thanks so much!

**Comment by klangman** [comment]
OK.. Thanks for your input. I'll be doing some testing over the next week or so before pushing all of this to cinnamon-spices. Open another issue if you hit any issues.
