### ISSUE TITLE
[Bug] Some application icons not recognized.

### ISSUE THREAD

**Issue by Patrock404** [klangman/CassiaWindowList#8]
Hi again, sorry if I'm bombarding you with all these bug reports.

I found a weird one. Some processes don't have their icons correctly displayed.
Minecraft, which runs as a Java process does not have its icon correctly displayed. In the example image, CobiWindowList is in the middle, and Cassia Window List is on the left. I'm not sure why this happens as this applet is a fork of CobiWindowList.

Anyway, I thought it was interesting. I'm really loving this applet, keep up the great work!

![minecraft](https://github.com/klangman/CassiaWindowList/assets/113575251/f455871e-21a3-4fb4-bc98-d355a144c9e0)

**Comment by klangman** [comment]
That is strange.. Is there any messages that appear in .xsession-errors when this window appears on the window-lists?

`tail -f .xsession-errors`

**Comment by Patrock404** [comment]
Yes, I get the warning:
`Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a0000b`

**Comment by klangman** [comment]
Are you sure the message appears right when the Minecraft window opens?

**Comment by Patrock404** [comment]
Yes.
https://github.com/klangman/CassiaWindowList/assets/113575251/5ab8dcf5-57ae-4f5d-9962-b230a2724e38

**Comment by klangman** [comment]
Hum... OK... That video helps, thanks! 

I am not sure if that message is related to the missing icon, I suspect that the same message would appear even without the CassiaWindowList instance active.

I'll compare my code to Cobi's and see if I can spot some difference that might explain the missing icon, but it's clearly a bug in my code somehow so thanks for reporting the issue!

**Comment by Patrock404** [comment]
I did some more testing, and I actually had the same issue with with CobiWindowList.
What happens in the video really confused me until I realized the applet is probably refreshed when moving from one zone to another.
https://github.com/klangman/CassiaWindowList/assets/113575251/c382d0b3-e7bc-4124-9f35-165665a0c0d2

Sure enough, if you refresh CassiaWindowList after the game client launches, the icon returns.
https://github.com/klangman/CassiaWindowList/assets/113575251/9869e577-c70e-408f-b914-c1b80340e05e

**Comment by klangman** [comment]
What about the default window list or the grouped window list. Do they have the same issue?

**Comment by Patrock404** [comment]
Just tested with grouped window list, it flashes the generic gear icon, then the correct icon takes over.

**Comment by klangman** [comment]
OK.. I was thinking of trying to post a delayed event to re-check if the icon can be found or look for some event that gets fired when the icon changes for a window. Since the grouped-window-list gets it right, I can just look to see what extra work it's doing to update when the icon is updated. I'll check it out later tonight.

**Comment by klangman** [comment]
I have pushed this change:

https://github.com/klangman/CassiaWindowList/commit/67865733f79e16f2012a3fbb02738b0e65fcf4e2

I hope it addresses the issue. If you have a chance, can you get this change and test it using Minecraft?

**Comment by Patrock404** [comment]
Just tested using Minecraft, working great!
